### ISSUE TITLE
Bro Can you Resolve this error? i have comitted to do this as my 4th year major project.

### ISSUE THREAD

**Issue by hariiprasad** [Chiragasourabh/Final-Year-Project#1]
![Screenshot (265)](https://user-images.githubusercontent.com/42040267/66121939-06cb0b00-e5fc-11e9-8439-ad09676c7d43.png)
![Screenshot (266)](https://user-images.githubusercontent.com/42040267/66121941-0763a180-e5fc-11e9-9c38-e7188fd2ae6a.png)

**Comment by hariiprasad** [comment]
@Chiragasourabh will be waiting for your response

**Comment by Chiragasourabh** [comment]
@hariiprasad  hey I think API key has reached maximum free hits. get a free API key from https://www.phishtank.com and replace the old one with new at line number 108 of PhishTankAPI.py file and try running. if you find any error write here. I'll get back to u.

**Comment by hariiprasad** [comment]
@Chiragasourabh Thank You So Much For Your Response. Will get back to you in Morning✌️.
